[package]
name = "nancy-server"
version = "0.1.0"
authors = ["wylited <wylited@gmail.com>"]
edition = "2021"
description = "The server backend for Nancy"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
